
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Operations
{
    using System;
    using UnityEngine.Networking;
    
    
    public class CreateRoomDeprecatedResponse: IDisposable
    {
        
        public string? ContentType { get; set; }
        
        
        public string? CreateRoomDeprecated400ApplicationJSONString { get; set; }
        
        
        public string? CreateRoomDeprecated402ApplicationJSONString { get; set; }
        
        
        public string? CreateRoomDeprecated403ApplicationJSONString { get; set; }
        
        
        public string? CreateRoomDeprecated404ApplicationJSONString { get; set; }
        
        
        public string? CreateRoomDeprecated500ApplicationJSONString { get; set; }
        
        
        public string? RoomId { get; set; }
        
        
        public int StatusCode { get; set; }
        
        
        public UnityWebRequest? RawResponse { get; set; }
        
        public void Dispose() {
            if (RawResponse != null) {
                RawResponse.Dispose();
            }
        }
    }
    
}