
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Operations
{
    using Hathora2.Models.Shared;
    using System;
    using UnityEngine.Networking;
    
    
    public class GetAppInfoResponse: IDisposable
    {
        /// <summary>
        /// Ok
        /// </summary>
        
        public Application? Application { get; set; }
        
        
        public string? ContentType { get; set; }
        
        
        public string? GetAppInfo404ApplicationJSONString { get; set; }
        
        
        public int StatusCode { get; set; }
        
        
        public UnityWebRequest? RawResponse { get; set; }
        
        public void Dispose() {
            if (RawResponse != null) {
                RawResponse.Dispose();
            }
        }
    }
    
}