
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Operations
{
    using Hathora2.Models.Shared;
    using Hathora2.Utils;
    
    
    public class ListActivePublicLobbiesDeprecatedRequest
    {
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")]
        public string AppId { get; set; }
        
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=local")]
        public bool? Local { get; set; }
        
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=region")]
        public Region? Region { get; set; }
        
    }
    
}