
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Operations
{
    using Hathora2.Models.Shared;
    using Hathora2.Utils;
    
    
    public class LoginNicknameRequest
    {
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public Models.Shared.LoginNicknameRequest LoginNicknameRequestValue { get; set; }
        
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")]
        public string AppId { get; set; }
        
    }
    
}