
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Operations
{
    using Hathora2.Utils;
    
    
    public class RunBuildRequest
    {
        [SpeakeasyMetadata("request:mediaType=multipart/form-data")]
        public RunBuildRequestBody RequestBody { get; set; }
        
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")]
        public string AppId { get; set; }
        
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=buildId")]
        public int BuildId { get; set; }
        
    }
    
}