/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApplicationWithDeploymentAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationWithDeploymentAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationWithDeploymentAllOf
        //private ApplicationWithDeploymentAllOf instance;

        public ApplicationWithDeploymentAllOfTests()
        {
            // TODO uncomment below to create an instance of ApplicationWithDeploymentAllOf
            //instance = new ApplicationWithDeploymentAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationWithDeploymentAllOf
        /// </summary>
        [Test]
        public void ApplicationWithDeploymentAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplicationWithDeploymentAllOf
            //Assert.IsType<ApplicationWithDeploymentAllOf>(instance);
        }

        /// <summary>
        /// Test the property 'Deployment'
        /// </summary>
        [Test]
        public void DeploymentTest()
        {
            // TODO unit test for the property 'Deployment'
        }
    }
}
