/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Build
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuildTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Build
        //private Build instance;

        public BuildTests()
        {
            // TODO uncomment below to create an instance of Build
            //instance = new Build();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Build
        /// </summary>
        [Test]
        public void BuildInstanceTest()
        {
            // TODO uncomment below to test "IsType" Build
            //Assert.IsType<Build>(instance);
        }

        /// <summary>
        /// Test the property 'RegionalContainerTags'
        /// </summary>
        [Test]
        public void RegionalContainerTagsTest()
        {
            // TODO unit test for the property 'RegionalContainerTags'
        }
        /// <summary>
        /// Test the property 'ImageSize'
        /// </summary>
        [Test]
        public void ImageSizeTest()
        {
            // TODO unit test for the property 'ImageSize'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Test]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'FinishedAt'
        /// </summary>
        [Test]
        public void FinishedAtTest()
        {
            // TODO unit test for the property 'FinishedAt'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Test]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'BuildId'
        /// </summary>
        [Test]
        public void BuildIdTest()
        {
            // TODO unit test for the property 'BuildId'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
    }
}
