/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePrivateLobbyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePrivateLobbyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePrivateLobbyRequest
        //private CreatePrivateLobbyRequest instance;

        public CreatePrivateLobbyRequestTests()
        {
            // TODO uncomment below to create an instance of CreatePrivateLobbyRequest
            //instance = new CreatePrivateLobbyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePrivateLobbyRequest
        /// </summary>
        [Test]
        public void CreatePrivateLobbyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePrivateLobbyRequest
            //Assert.IsType<CreatePrivateLobbyRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InitialConfig'
        /// </summary>
        [Test]
        public void InitialConfigTest()
        {
            // TODO unit test for the property 'InitialConfig'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
    }
}
