/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentAllOf
        //private DeploymentAllOf instance;

        public DeploymentAllOfTests()
        {
            // TODO uncomment below to create an instance of DeploymentAllOf
            //instance = new DeploymentAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentAllOf
        /// </summary>
        [Test]
        public void DeploymentAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentAllOf
            //Assert.IsType<DeploymentAllOf>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'RequestedMemoryMB'
        /// </summary>
        [Test]
        public void RequestedMemoryMBTest()
        {
            // TODO unit test for the property 'RequestedMemoryMB'
        }
        /// <summary>
        /// Test the property 'RequestedCPU'
        /// </summary>
        [Test]
        public void RequestedCPUTest()
        {
            // TODO unit test for the property 'RequestedCPU'
        }
        /// <summary>
        /// Test the property 'DeploymentId'
        /// </summary>
        [Test]
        public void DeploymentIdTest()
        {
            // TODO unit test for the property 'DeploymentId'
        }
        /// <summary>
        /// Test the property 'BuildId'
        /// </summary>
        [Test]
        public void BuildIdTest()
        {
            // TODO unit test for the property 'BuildId'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
    }
}
