/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentConfigEnvInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentConfigEnvInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentConfigEnvInner
        //private DeploymentConfigEnvInner instance;

        public DeploymentConfigEnvInnerTests()
        {
            // TODO uncomment below to create an instance of DeploymentConfigEnvInner
            //instance = new DeploymentConfigEnvInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentConfigEnvInner
        /// </summary>
        [Test]
        public void DeploymentConfigEnvInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentConfigEnvInner
            //Assert.IsType<DeploymentConfigEnvInner>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
