/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ExposedPort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExposedPortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExposedPort
        //private ExposedPort instance;

        public ExposedPortTests()
        {
            // TODO uncomment below to create an instance of ExposedPort
            //instance = new ExposedPort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExposedPort
        /// </summary>
        [Test]
        public void ExposedPortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExposedPort
            //Assert.IsType<ExposedPort>(instance);
        }

        /// <summary>
        /// Test the property 'TransportType'
        /// </summary>
        [Test]
        public void TransportTypeTest()
        {
            // TODO unit test for the property 'TransportType'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
