/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PickRoomExcludeKeyofRoomAllocations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PickRoomExcludeKeyofRoomAllocationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PickRoomExcludeKeyofRoomAllocations
        //private PickRoomExcludeKeyofRoomAllocations instance;

        public PickRoomExcludeKeyofRoomAllocationsTests()
        {
            // TODO uncomment below to create an instance of PickRoomExcludeKeyofRoomAllocations
            //instance = new PickRoomExcludeKeyofRoomAllocations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PickRoomExcludeKeyofRoomAllocations
        /// </summary>
        [Test]
        public void PickRoomExcludeKeyofRoomAllocationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PickRoomExcludeKeyofRoomAllocations
            //Assert.IsType<PickRoomExcludeKeyofRoomAllocations>(instance);
        }

        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'RoomId'
        /// </summary>
        [Test]
        public void RoomIdTest()
        {
            // TODO unit test for the property 'RoomId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CurrentAllocation'
        /// </summary>
        [Test]
        public void CurrentAllocationTest()
        {
            // TODO unit test for the property 'CurrentAllocation'
        }
    }
}
