/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessWithRooms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessWithRoomsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessWithRooms
        //private ProcessWithRooms instance;

        public ProcessWithRoomsTests()
        {
            // TODO uncomment below to create an instance of ProcessWithRooms
            //instance = new ProcessWithRooms();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessWithRooms
        /// </summary>
        [Test]
        public void ProcessWithRoomsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessWithRooms
            //Assert.IsType<ProcessWithRooms>(instance);
        }

        /// <summary>
        /// Test the property 'EgressedBytes'
        /// </summary>
        [Test]
        public void EgressedBytesTest()
        {
            // TODO unit test for the property 'EgressedBytes'
        }
        /// <summary>
        /// Test the property 'IdleSince'
        /// </summary>
        [Test]
        public void IdleSinceTest()
        {
            // TODO unit test for the property 'IdleSince'
        }
        /// <summary>
        /// Test the property 'ActiveConnections'
        /// </summary>
        [Test]
        public void ActiveConnectionsTest()
        {
            // TODO unit test for the property 'ActiveConnections'
        }
        /// <summary>
        /// Test the property 'RoomSlotsAvailable'
        /// </summary>
        [Test]
        public void RoomSlotsAvailableTest()
        {
            // TODO unit test for the property 'RoomSlotsAvailable'
        }
        /// <summary>
        /// Test the property 'Draining'
        /// </summary>
        [Test]
        public void DrainingTest()
        {
            // TODO unit test for the property 'Draining'
        }
        /// <summary>
        /// Test the property 'TerminatedAt'
        /// </summary>
        [Test]
        public void TerminatedAtTest()
        {
            // TODO unit test for the property 'TerminatedAt'
        }
        /// <summary>
        /// Test the property 'StoppingAt'
        /// </summary>
        [Test]
        public void StoppingAtTest()
        {
            // TODO unit test for the property 'StoppingAt'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Test]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'StartingAt'
        /// </summary>
        [Test]
        public void StartingAtTest()
        {
            // TODO unit test for the property 'StartingAt'
        }
        /// <summary>
        /// Test the property 'RoomsPerProcess'
        /// </summary>
        [Test]
        public void RoomsPerProcessTest()
        {
            // TODO unit test for the property 'RoomsPerProcess'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Test]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'DeploymentId'
        /// </summary>
        [Test]
        public void DeploymentIdTest()
        {
            // TODO unit test for the property 'DeploymentId'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'Rooms'
        /// </summary>
        [Test]
        public void RoomsTest()
        {
            // TODO unit test for the property 'Rooms'
        }
        /// <summary>
        /// Test the property 'TotalRooms'
        /// </summary>
        [Test]
        public void TotalRoomsTest()
        {
            // TODO unit test for the property 'TotalRooms'
        }
    }
}
