/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Hathora.Cloud.Sdk.Client.OpenAPIDateConverter;

namespace Hathora.Cloud.Sdk.Model
{
    /// <summary>
    /// ApplicationWithDeploymentAllOf
    /// </summary>
    [DataContract(Name = "ApplicationWithDeployment_allOf")]
    public partial class ApplicationWithDeploymentAllOf : IEquatable<ApplicationWithDeploymentAllOf>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationWithDeploymentAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApplicationWithDeploymentAllOf()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationWithDeploymentAllOf" /> class.
        /// </summary>
        /// <param name="deployment">deployment (required).</param>
        public ApplicationWithDeploymentAllOf(Deployment deployment = default(Deployment))
        {
            // to ensure "deployment" is required (not null)
            if (deployment == null)
            {
                throw new ArgumentNullException("deployment is a required property for ApplicationWithDeploymentAllOf and cannot be null");
            }
            this.Deployment = deployment;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Deployment
        /// </summary>
        [DataMember(Name = "deployment", IsRequired = true, EmitDefaultValue = true)]
        public Deployment Deployment { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplicationWithDeploymentAllOf {\n");
            sb.Append("  Deployment: ").Append(Deployment).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApplicationWithDeploymentAllOf);
        }

        /// <summary>
        /// Returns true if ApplicationWithDeploymentAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of ApplicationWithDeploymentAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicationWithDeploymentAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Deployment == input.Deployment ||
                    (this.Deployment != null &&
                    this.Deployment.Equals(input.Deployment))
                )
                && (this.AdditionalProperties.Count == input.AdditionalProperties.Count && !this.AdditionalProperties.Except(input.AdditionalProperties).Any());
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Deployment != null)
                {
                    hashCode = (hashCode * 59) + this.Deployment.GetHashCode();
                }
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
