/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Hathora.Cloud.Sdk.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Hathora.Cloud.Sdk.Model
{
    /// <summary>
    /// ConnectionInfo
    /// </summary>
    [JsonConverter(typeof(ConnectionInfoJsonConverter))]
    [DataContract(Name = "ConnectionInfo")]
    public partial class ConnectionInfo : AbstractOpenAPISchema, IEquatable<ConnectionInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionInfo" /> class
        /// with the <see cref="StartingConnectionInfo" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of StartingConnectionInfo.</param>
        public ConnectionInfo(StartingConnectionInfo actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionInfo" /> class
        /// with the <see cref="ActiveConnectionInfo" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ActiveConnectionInfo.</param>
        public ConnectionInfo(ActiveConnectionInfo actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ActiveConnectionInfo))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(StartingConnectionInfo))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ActiveConnectionInfo, StartingConnectionInfo");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `StartingConnectionInfo`. If the actual instance is not `StartingConnectionInfo`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of StartingConnectionInfo</returns>
        public StartingConnectionInfo GetStartingConnectionInfo()
        {
            return (StartingConnectionInfo)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ActiveConnectionInfo`. If the actual instance is not `ActiveConnectionInfo`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ActiveConnectionInfo</returns>
        public ActiveConnectionInfo GetActiveConnectionInfo()
        {
            return (ActiveConnectionInfo)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConnectionInfo {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ConnectionInfo.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ConnectionInfo
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ConnectionInfo</returns>
        public static ConnectionInfo FromJson(string jsonString)
        {
            ConnectionInfo newConnectionInfo = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newConnectionInfo;
            }

            try
            {
                newConnectionInfo = new ConnectionInfo(JsonConvert.DeserializeObject<ActiveConnectionInfo>(jsonString, ConnectionInfo.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newConnectionInfo;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ActiveConnectionInfo: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newConnectionInfo = new ConnectionInfo(JsonConvert.DeserializeObject<StartingConnectionInfo>(jsonString, ConnectionInfo.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newConnectionInfo;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into StartingConnectionInfo: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConnectionInfo);
        }

        /// <summary>
        /// Returns true if ConnectionInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ConnectionInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConnectionInfo input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

    }

    /// <summary>
    /// Custom JSON converter for ConnectionInfo
    /// </summary>
    public class ConnectionInfoJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ConnectionInfo).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ConnectionInfo.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
