/*
 * Hathora Cloud API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using NUnit.Framework;

using Hathora.Cloud.Sdk.Client;
using Hathora.Cloud.Sdk.Api;
// uncomment below to import models
//using Hathora.Cloud.Sdk.Model;

namespace Hathora.Cloud.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing DiscoveryV1Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DiscoveryV1ApiTests : IDisposable
    {
        private DiscoveryV1Api instance;

        public DiscoveryV1ApiTests()
        {
            instance = new DiscoveryV1Api();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscoveryV1Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DiscoveryV1Api
            //Assert.IsType<DiscoveryV1Api>(instance);
        }

        /// <summary>
        /// Test GetPingServiceEndpoints
        /// </summary>
        [Test]
        public void GetPingServiceEndpointsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetPingServiceEndpoints();
            //Assert.IsType<List<DiscoveryResponseInner>>(response);
        }
    }
}
