
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Shared
{
    using Newtonsoft.Json;
    
    
    public class AchPaymentMethod
    {
        [JsonProperty("bankName")]
        public string? BankName { get; set; }
        
        [JsonProperty("last4")]
        public string? Last4 { get; set; }
        
    }
    
}