
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Shared
{
    using Newtonsoft.Json;
    
    
    /// <summary>
    /// Enable google auth for your application.
    /// </summary>
    public class AuthConfigurationGoogle
    {
        /// <summary>
        /// A Google generated token representing the developer's credentials for [Google's API Console](https://console.cloud.google.com/apis/dashboard?pli=1&project=discourse-login-388921). Learn how to get a `clientId` [here](https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid).
        /// </summary>
        [JsonProperty("clientId")]
        public string ClientId { get; set; }
        
    }
    
}