
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Shared
{

    
    
    /// <summary>
    /// User input to initialize the game state. Object must be smaller than 64KB.
    /// </summary>
    public class LobbyInitialConfig
    {
    }
    
}