
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Shared
{
    using Newtonsoft.Json;
    
    
    public class SetLobbyStateRequest
    {
        /// <summary>
        /// JSON blob to store metadata for a room. Must be smaller than 1MB.
        /// </summary>
        [JsonProperty("state")]
        public SetLobbyStateRequestState State { get; set; }
        
    }
    
}