
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora2.Models.Shared
{
    using Newtonsoft.Json;
    
    
    public class VerificationEmailRequest
    {
        [JsonProperty("userId")]
        public string UserId { get; set; }
        
    }
    
}